"""Initial migration with frais fields

Revision ID: e23588e3971c
Revises: 
Create Date: 2026-01-30 22:03:29.075565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e23588e3971c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Immeubles table
    op.create_table('immeubles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('nom', sa.String(length=200), nullable=False),
        sa.Column('adresse', sa.String(length=500), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Bureaux table
    op.create_table('bureaux',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('immeuble_id', sa.Integer(), nullable=False),
        sa.Column('numero', sa.String(length=50), nullable=False),
        sa.Column('etage', sa.String(length=50), nullable=True),
        sa.Column('surface_m2', sa.Float(), nullable=True),
        sa.Column('est_disponible', sa.Boolean(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['immeuble_id'], ['immeubles.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('immeuble_id', 'numero', name='uq_immeuble_bureau_numero')
    )
    
    # Locataires table
    op.create_table('locataires',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('nom', sa.String(length=200), nullable=False),
        sa.Column('telephone', sa.String(length=50), nullable=True),
        sa.Column('email', sa.String(length=200), nullable=True),
        sa.Column('cin', sa.String(length=50), nullable=True),
        sa.Column('raison_sociale', sa.String(length=200), nullable=True),
        sa.Column('statut', sa.Enum('ACTIF', 'HISTORIQUE', name='statutlocataire'), nullable=True),
        sa.Column('commentaires', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Contrats table
    op.create_table('contrats',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('Locataire_id', sa.Integer(), nullable=False),
        sa.Column('date_debut', sa.Date(), nullable=False),
        sa.Column('date_derniere_augmentation', sa.Date(), nullable=True),
        sa.Column('montant_premier_mois', sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column('montant_mensuel', sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column('montant_caution', sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column('montant_pas_de_porte', sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column('compteur_steg', sa.String(length=100), nullable=True),
        sa.Column('compteur_sonede', sa.String(length=100), nullable=True),
        sa.Column('est_resilie_col', sa.Boolean(), nullable=True),
        sa.Column('date_resiliation', sa.Date(), nullable=True),
        sa.Column('motif_resiliation', sa.Text(), nullable=True),
        sa.Column('conditions', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['Locataire_id'], ['locataires.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Paiements table with frais fields
    op.create_table('paiements',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('Locataire_id', sa.Integer(), nullable=False),
        sa.Column('contrat_id', sa.Integer(), nullable=False),
        sa.Column('type_paiement', sa.Enum('LOYER', 'CAUTION', 'PAS_DE_PORTE', 'AUTRE', name='typepaiement'), nullable=False),
        sa.Column('montant_total', sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column('frais_menage', sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column('frais_sonede', sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column('frais_steg', sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column('date_paiement', sa.Date(), nullable=False),
        sa.Column('date_debut_periode', sa.Date(), nullable=True),
        sa.Column('date_fin_periode', sa.Date(), nullable=True),
        sa.Column('commentaire', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['Locataire_id'], ['locataires.id'], ),
        sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Audit logs table
    op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('table_nom', sa.String(length=100), nullable=False),
        sa.Column('entite_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('donnees_avant', sa.JSON(), nullable=True),
        sa.Column('donnees_apres', sa.JSON(), nullable=True),
        sa.Column('utilisateur', sa.String(length=100), nullable=True),
        sa.Column('ip_address', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Document tree configs table
    op.create_table('document_tree_configs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('tree_structure', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('entity_type')
    )
    
    # Documents table
    op.create_table('documents',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=False),
        sa.Column('folder_path', sa.String(length=500), nullable=False),
        sa.Column('filename', sa.String(length=500), nullable=False),
        sa.Column('original_name', sa.String(length=500), nullable=False),
        sa.Column('file_type', sa.String(length=100), nullable=True),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Association table for contrat-bureau many-to-many relationship
    op.create_table('contrat_bureau',
        sa.Column('contrat_id', sa.Integer(), nullable=False),
        sa.Column('bureau_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['bureau_id'], ['bureaux.id'], ),
        sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ),
        sa.PrimaryKeyConstraint('contrat_id', 'bureau_id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('document_tree_configs')
    op.drop_table('audit_logs')
    op.drop_table('paiements')
    op.drop_table('contrats')
    op.drop_table('locataires')
    op.drop_table('bureaux')
    op.drop_table('immeubles')
    op.drop_table('contrat_bureau')
    
    # Drop enum types
    op.execute('DROP TYPE IF EXISTS typepaiement')
    op.execute('DROP TYPE IF EXISTS statutlocataire')
    # ### end Alembic commands ###
